### PR TITLE
Fix on 3.74.

### PR DESCRIPTION
**Pull request by KuromeSan**
i am doing this right .. right?

### CODE REVIEW

**Comment by StarWolf3000** [comment]
This will break 3.69-3.72, which also require h-encore². Better:
```cpp
        else if (vita->getDeviceVersion() <= "3.74")
```

**Comment by KuromeSan** [comment]
but i read the code dumbly and for some reason thought the order was the other way around my bad.

**Comment by KuromeSan** [comment]
perhaps we should actually change this to a simple 'else' case so that it works even if a newer firmware than 3.74 is released?

**Comment by StarWolf3000** [comment]
Yeah, unless future updates require a newer h-encore than h-encore², going with a simple `else` for the case of h-encore² will work just fine.

**Comment by Mrwinkle-dot** [comment]
> 

Ok

**Comment by KuromeSan** [comment]
@Mrwinkle-dot here i compiled it .. [FinalHE_v1.92_win32.zip](https://github.com/soarqin/finalhe/files/8662405/FinalHE_v1.92_win32.zip)

**Comment by Mrwinkle-dot** [comment]
Holy shit it's working thank you so much you guys

**Comment by mayankshekh87** [comment]
> @Mrwinkle-dot here i compiled it .. [FinalHE_v1.92_win32.zip](https://github.com/soarqin/finalhe/files/8662405/FinalHE_v1.92_win32.zip)

For me h-encore is stuck at Exiting for 10 mins, is that normal?

**Comment by KuromeSan** [comment]
> For me h-encore is stuck at Exiting for 10 mins, is that normal?

it worked on my 3.74 pstv...

mm CMA has always been finicky

**Comment by Yoti** [comment]
@soarqin plz merge and release

**Comment by KuromeSan** [comment]
> > @Mrwinkle-dot here i compiled it .. [FinalHE_v1.92_win32.zip](https://github.com/soarqin/finalhe/files/8662405/FinalHE_v1.92_win32.zip)
> 
> For me h-encore is stuck at Exiting for 10 mins, is that normal?

oh wait, im pretty sure for that you have to click 'install henkaku' first. and hten you can click exit

**Comment by AntHJ** [comment]
> > @Mrwinkle-dot here i compiled it .. [FinalHE_v1.92_win32.zip](https://github.com/soarqin/finalhe/files/8662405/FinalHE_v1.92_win32.zip)
> 
> For me h-encore is stuck at Exiting for 10 mins, is that normal?

I had the same issue..
delete the installed Hencore, close FinalHE and start again..
if its the same again, dont select trim..

**Comment by Donnit86** [comment]
> > > @Mrwinkle-dot here i compiled it .. [FinalHE_v1.92_win32.zip](https://github.com/soarqin/finalhe/files/8662405/FinalHE_v1.92_win32.zip)
> > 
> > 
> > For me h-encore is stuck at Exiting for 10 mins, is that normal?
> 
> I had the same issue.. delete the installed Hencore, close FinalHE and start again.. if its the same again, try again but dont select trim..

Thanks AntHJ
I tried that but it failed.

I worte the whole ordeal on Discord, here is a copy.

_Hello everyone, I just got a vita 1104 and am trying to install Ensō and so on.
I am following the guide on vita.hacks.guide.
I was able to upgrade to 3.74.
Then using FinalHE_v1.92_win32.zip was able to install VitaDeploy and h encore. So far so good.
H encore started properly on the second time. I exited it right away, it installed henkaku. I Enabled Unsafe Homebrew.
I clicked on "Quick 3.65 Install" and that when troubles really started. It displayed an error message. Tried again and got another error message but different one.
Checked the system version, it was on 3.73 followed by Japanese characters.
I restarted to start over. But from then, H encore will keep freezing on exciting.
I tried many times, always froze. I removed it and reinstalled it through FinalHE, same problem. I removed it again and re installed it but this time not using the trimming option. Same error.
After each freeze I have to restart the vita through the safe mode for it to be back on the main menu.
If anyone has any ideas, that would be awesome.
Thanks._

**Comment by Shell94845** [comment]
Hi, i got the 3.74 firmware and every time i dowload the last version of finalHE from soarqin page i get the first version h encore on my vita did anyone knows how i can get h encore 2 ? I'm a beginner in this.
I also have the long white screen everytime i try to open h encore.

**Comment by StarWolf3000** [comment]
> Hi, i got the 3.74 firmware and every time i dowload the last version of finalHE from soarqin page i get the first version h encore on my vita did anyone knows how i can get h encore 2 ? I'm a beginner in this. I also have the long white screen everytime i try to open h encore.

Quite a few messages above you: [FinalHE_v1.92_win32.zip](https://github.com/soarqin/finalhe/files/8662405/FinalHE_v1.92_win32.zip)

**Comment by Shell94845** [comment]
> > Hi, i got the 3.74 firmware and every time i dowload the last version of finalHE from soarqin page i get the first version h encore on my vita did anyone knows how i can get h encore 2 ? I'm a beginner in this. I also have the long white screen everytime i try to open h encore.
> 
> Quite a few messages above you: [FinalHE_v1.92_win32.zip]

Yeah i download it several times today and i was getting the same h encore1. I contacted the guy who got the same issue than me on reddit, he sent me the exact same file but this time it was good.

I got h encore 2 right now and everything seems to work now.

Thanks again guys for your work.

**Comment by traven89** [comment]
> > > Hi, i got the 3.74 firmware and every time i dowload the last version of finalHE from soarqin page i get the first version h encore on my vita did anyone knows how i can get h encore 2 ? I'm a beginner in this. I also have the long white screen everytime i try to open h encore.
> > 
> > 
> > Quite a few messages above you: [FinalHE_v1.92_win32.zip]
> 
> Yeah i download it several times today and i was getting the same h encore1. I contacted the guy who got the same issue than me on reddit, he sent me the exact same file but this time it was good.
> 
> I got h encore 2 right now and everything seems to work now.
> 
> Thanks again guys for your work.

Any chance i could get this file?

**Comment by Xanderwik** [comment]
> > @Mrwinkle-dot here i compiled it .. [FinalHE_v1.92_win32.zip](https://github.com/soarqin/finalhe/files/8662405/FinalHE_v1.92_win32.zip)
> 
> For me h-encore is stuck at Exiting for 10 mins, is that normal?

Clear taihen, then install henkaku, then exit.

**Comment by Yoti** [comment]
@soarqin please build and upload new version to the releases tab.

**Comment by Shell94845** [comment]
> > > > Hi, i got the 3.74 firmware and every time i dowload the last version of finalHE from soarqin page i get the first version h encore on my vita did anyone knows how i can get h encore 2 ? I'm a beginner in this. I also have the long white screen everytime i try to open h encore.
> > > 
> > > 
> > > Quite a few messages above you: [FinalHE_v1.92_win32.zip]
> > 
> > 
> > Yeah i download it several times today and i was getting the same h encore1. I contacted the guy who got the same issue than me on reddit, he sent me the exact same file but this time it was good.
> > I got h encore 2 right now and everything seems to work now.
> > Thanks again guys for your work.
> 
> Any chance i could get this file?


https://github.com/soarqin/finalhe/files/8662405/FinalHE_v1.92_win32.zip 
https://www.youtube.com/watch?v=eDO7f9ciLU8 

With this you should get it done pretty fast

**Comment by Josh323** [comment]
I'm trying to download this file and my computer is not opening the"h-encore" app I been having the same problem as all these people stated I get h-encore 1 download on the vita

**Pull request merged**
